Tecnativa/docker-duplicity

Dockerfile
Fixes the installation of `PyNaCl`, which is failing with the following error:
> Could not find a version that satisfies the requirement cffi>=1.4.1 (from versions: )
> No matching distribution found for cffi>=1.4.1
Related Alpine bug report: https://bugs.alpinelinux.org/issues/9475
=> [FIX] Pin 'PyNaCl' version

Dockerfile
pexpect should be installed so `pexpect+sftp://user@host//folder` is supported.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866062
=> Install pexpect

README.md, bin/jobrunner
Without this patch, we were obtaining this error due to the change to Python 3.8:
```
INFO:jobrunner:2020-05-06 17:51:35.962457 UTC - Running daily jobs
INFO:jobrunner:Running job 200: `psql -0Atd postgres -c "SELECT datname FROM pg_database WHERE NOT datistemplate AND datname != 'postgres'" | xargs -0tI DB pg_dump --dbname DB --no-owner --no-privileges --file "/mnt/backup/src/DB.sql"`
Traceback (most recent call last):
File "/etc/periodic/daily/jobrunner", line 77, in <module>
logging.log(logging.INFO if success else logging.ERROR, "\n".join(log))
TypeError: sequence item 7: expected str instance, bytes found
```
=> Force text mode in subprocess

Dockerfile
The current swift support does not include keystone credential functionality required by newer swift API's. This PR adds them and its build dependencies.
=> [ADD] Support for Openstack V2+ api endpoints

Dockerfile
Postgresql client should update to latest version on build.
Current latest is version 12.4
This should fix incompatibility problems with Postgresql v13.
TT26463
=> Update duplicity packages and postgres libraries

.github/workflows/ci.yaml, .pre-commit-config.yaml, Dockerfile, README.md
Adds `DBS_TO_EXCLUDE` environment variable to filter `pg_dump` target dbs. 
Allows passing a regex to filter DBs.
Also updated prettier/prettier to prettier/pre-commit (#prettiermageddon)
@Tecnativa
TT26621
=> Add dbs to exclude (+ fix prettier)

Dockerfile
Current `grep` version in the image does not allow for complex options, neither does it support the `--null-data` one, which we need to filter the DBs that shouldn't be backed up.
This ensures we have the correct grep version.
TT26621
ping @Yajo
=> Fix grep installation

Dockerfile, poetry.lock, pyproject.toml, requirements.txt
Dependency solving is now handled by poetry locally and pinned in lock
file and exported to requirements.txt
Duplicity package is now installed from pypi instead of from tar
`azure-mgmt-storage` had to be removed and some other dependencies pinned
at older versions to ensure dependency compatibility.
Closes #30.
=> Fix python packages installation

Dockerfile
The $ sign was not being escaped from the Dockerfile, so the `grep` was being set at build time with the default value of "$^".
This escapes the sign, same as with $SRC a little ahead in the expression, ensuring the correct value is assumed.
Old behaviour:
```
/ # echo $JOB_200_WHAT
psql -0Atd postgres -c "SELECT datname FROM pg_database WHERE NOT datistemplate AND datname != 'postgres'" | grep --null-data --invert-match -E "$^" | xargs -0tI DB pg_dump --dbname DB --no-owner --no-privileges --file "$SRC/DB.sql"
```
After this fix:
```
bash-5.0# echo $JOB_200_WHAT 
psql -0Atd postgres -c "SELECT datname FROM pg_database WHERE NOT datistemplate AND datname != 'postgres'" | grep --null-data --invert-match -E "$DBS_TO_EXCLUDE" | xargs -0tI DB pg_dump --dbname DB --no-owner --no-privileges …
```
=> Fix DB excludes expression

.pre-commit-config.yaml, Dockerfile
Because of the command pipelining, the return code of `JOB_200_WHAT` wasn't taking in consideration the result of the first `psql` command.
This ensures the command fails when any command exits with a return code different from 0, and keeps that exit code.
TT27204
**Example**:
Before, when you had a wrong password, for example:
```bash
bash-5.0# psql -0Atd postgres -c "SELECT datname FROM pg_database WHERE NOT datistemplate AND datname != 'postgres'" | grep --null-data --invert-match -E \"\$DBS_TO_EXCLUDE\" | xargs -0tI DB echo DB
psql: error: could not connect to server: FATAL:  password authentication failed for user "myuser"
bash-5.0# echo $?
0
```
After this fix:
```bash
bash-5.0# set -euo pipefail; psql -0Atd postgres -c "SELECT datname FROM pg_database WHERE NOT datistemplate AND …
```
=> Fix false positive in psql command

.github/workflows/cd.yaml
Use **Github Container Registry** instead of deprecated Github packages
Update to **build-push-action v2**
Start using **buildx**
This should contribute to fixing the latest build errors.
ping @Yajo
=> Update Github CI and CD

.github/workflows/cd.yaml
Push to tecnatva/duplicity instead of tecnativa/docker-duplicity
Fixes https://github.com/Tecnativa/docker-duplicity/issues/51
=> Fix DockerHub repo naming issues

.github/workflows/cd.yaml, Dockerfile, tests/test_service.py
This reverts commit 09ec1a5d4779e5273cf17310f6388b14725ef70b and adds a test to make sure this regression doesn't happen again.
@Tecnativa TT27819
=> Install correct Posgresql version (13.0)

Dockerfile, poetry.lock, pyproject.toml, requirements.txt
The Requests package through 2.19.1 before 2018-09-14 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network. (CVE-2018-18074)
We should abandon that old package in favour of a most recent one.
We need to remove the mediafire backend to do so.
=> Update requests dependency (removing mediafire backend)

.github/workflows/dependabot-merge.yml
From https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
=> Add workflow to auto-merge dependabot PRs

.pre-commit-config.yaml
To avoid the isort problem (PyCQA/isort#2077)
@Tecnativa
=> [FIX] Update isort version on pre-commit

Dockerfile, README.md, bin/jobrunner
Add environment variable `SMTP_ALWAYS` to allow limiting SMTP reports to those where jobs failed. Preserve current behaviour by defaulting to `SMTP_ALWAYS=1`.
I took some liberties rearranging the order of `SMTP_*` variables in the Dockerfile to match those in the README, feel free to undo those changes if they were in that order for some reason.
=> [IMP] Conditional SMTP reporting

Dockerfile, bin/entrypoint, tests/conftest.py, tests/test_service.py
This PR adds support for postgres flavours with explicit version...
NOTE: pg_dump 9.6 is not installable due to the alpine version used. So... doodba-copier-template can't up the backup service when use postgresql 9.6
=> [IMP] Postgres images with explicit version

Dockerfile, bin/jobrunner
=> [DCK] Downgrade python version to 3.11 on Dockerfile due to incompatibilities between Python 3.12 and Duplicity 1.2.3

README.md, bin/jobrunner, poetry.lock, pyproject.toml
Added dependency: `requests` since the python version used doesn't support request timeouts in the standard library.
I catch network related exceptions so other jobs run even on ping failure, assuming that the healthcheck would notify users if that happens.
Tested with docker compose:
```yml
services:
db:
image: postgres:15.4-alpine
environment:
POSTGRES_PASSWORD: mypass
POSTGRES_USER: myuser
POSTGRES_DB: somedb
networks:
- test
backup:
image: duplicity
hostname: my.postgres.backup
volumes:
- ./src:/mnt/backup/src
- ./dst:/mnt/backup/dst
- ./bin/jobrunner:/etc/periodic/15min/jobrunner
environment:
PGHOST: db # This is the default
PGPASSWORD: mypass
PGUSER: myuser
DST: file:///mnt/backup/dst
PASSPHRASE: example backkup encryption secret
JOB_200_WHEN: 15min daily weekly
JOB_300_WHEN: 15min …
```
=> Add support for pinging healthchecks.io and uptime-kuma

Dockerfile
CC @Tecnativa TT48361
The previous one referenced version 13 of PostgreSQL, as seen in the Alpine documentation: https://alpinelinux.org/posts/Alpine-3.14.0-released.html. To fix this issue, the latest Alpine release with PostgreSQL 12 was sought, which is version 3.12. This was also confirmed in the documentation: https://alpinelinux.org/posts/Alpine-3.12.0-released.html
This will fix test assertion error (https://github.com/Tecnativa/doodba-copier-template/actions/runs/8139020573/job/22241212135#step:14:122) on https://github.com/Tecnativa/doodba-copier-template
=> [FIX] Changed the PostgreSQL 12 repository.

README.md
Duplicity moved to [gitlab](https://gitlab.com/duplicity/duplicity)
=> [IMP] DOCS: Update links to new duplicity website
